[package]
name = "fustfood"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
# dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["web", "router"] }
dioxus = { version = "0.5.0-alpha.0", features = ["web", "router"] }
tokio = { version = "1.36.0", features = ["time"] }
wasm-bindgen = "0.2.89"

[dependencies.web-sys]
version = "0.3"
features = [
]
